# A R script to read in files generated by the `sna1` model, generate inut files
# for CASAL, run casal, read in CASAL output files, and generate a file of parameter
# estimates to be read by the `sna1` model unit tests

# TODO This is just a placeholder implementation which writes a parameter estimates file
cat(
	'B0_EN ', 99046, '\n',
	'B0_HG ', 208257, '\n',
	'B0_BP ', 99592.7, '\n',
	file='output/casal-estimates.txt',
	sep=''
)
